
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/smidr/.sbx-denybin/"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/nodejs/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Program Files/GnuPG/bin/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/smidr/AppData/Roaming/npm/"
      - "C:/Program Files (x86)/Nmap/"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/"
    searched_directories:
      - "C:/Users/smidr/.sbx-denybin/ninja-build.com"
      - "C:/Users/smidr/.sbx-denybin/ninja-build.exe"
      - "C:/Users/smidr/.sbx-denybin/ninja-build"
      - "C:/Users/smidr/.sbx-denybin/ninja.com"
      - "C:/Users/smidr/.sbx-denybin/ninja.exe"
      - "C:/Users/smidr/.sbx-denybin/ninja"
      - "C:/Users/smidr/.sbx-denybin/samu.com"
      - "C:/Users/smidr/.sbx-denybin/samu.exe"
      - "C:/Users/smidr/.sbx-denybin/samu"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/ninja-build.com"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/ninja-build.exe"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/ninja-build"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/ninja.com"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/ninja.exe"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/ninja"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/samu.com"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/samu.exe"
      - "C:/Users/smidr/.codex/tmp/arg0/codex-arg0uduYho/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "C:/ProgramData/chocolatey/bin/ninja-build.com"
      - "C:/ProgramData/chocolatey/bin/ninja-build.exe"
      - "C:/ProgramData/chocolatey/bin/ninja-build"
      - "C:/ProgramData/chocolatey/bin/ninja.com"
      - "C:/ProgramData/chocolatey/bin/ninja.exe"
      - "C:/ProgramData/chocolatey/bin/ninja"
      - "C:/ProgramData/chocolatey/bin/samu.com"
      - "C:/ProgramData/chocolatey/bin/samu.exe"
      - "C:/ProgramData/chocolatey/bin/samu"
      - "C:/Program Files/nodejs/ninja-build.com"
      - "C:/Program Files/nodejs/ninja-build.exe"
      - "C:/Program Files/nodejs/ninja-build"
      - "C:/Program Files/nodejs/ninja.com"
      - "C:/Program Files/nodejs/ninja.exe"
      - "C:/Program Files/nodejs/ninja"
      - "C:/Program Files/nodejs/samu.com"
      - "C:/Program Files/nodejs/samu.exe"
      - "C:/Program Files/nodejs/samu"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.com"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/samu"
      - "C:/Program Files/GnuPG/bin/ninja-build.com"
      - "C:/Program Files/GnuPG/bin/ninja-build.exe"
      - "C:/Program Files/GnuPG/bin/ninja-build"
      - "C:/Program Files/GnuPG/bin/ninja.com"
      - "C:/Program Files/GnuPG/bin/ninja.exe"
      - "C:/Program Files/GnuPG/bin/ninja"
      - "C:/Program Files/GnuPG/bin/samu.com"
      - "C:/Program Files/GnuPG/bin/samu.exe"
      - "C:/Program Files/GnuPG/bin/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/smidr/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/ninja-build.com"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/ninja-build.exe"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/ninja-build"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/ninja.com"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/ninja.exe"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/ninja"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/samu.com"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/samu.exe"
      - "C:/Users/smidr/AppData/Local/PowerToys/DSCModules/samu"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/smidr/AppData/Local/Programs/Microsoft VS Code/bin/samu"
      - "C:/Users/smidr/AppData/Roaming/npm/ninja-build.com"
      - "C:/Users/smidr/AppData/Roaming/npm/ninja-build.exe"
      - "C:/Users/smidr/AppData/Roaming/npm/ninja-build"
      - "C:/Users/smidr/AppData/Roaming/npm/ninja.com"
      - "C:/Users/smidr/AppData/Roaming/npm/ninja.exe"
      - "C:/Users/smidr/AppData/Roaming/npm/ninja"
      - "C:/Users/smidr/AppData/Roaming/npm/samu.com"
      - "C:/Users/smidr/AppData/Roaming/npm/samu.exe"
      - "C:/Users/smidr/AppData/Roaming/npm/samu"
      - "C:/Program Files (x86)/Nmap/ninja-build.com"
      - "C:/Program Files (x86)/Nmap/ninja-build.exe"
      - "C:/Program Files (x86)/Nmap/ninja-build"
      - "C:/Program Files (x86)/Nmap/ninja.com"
      - "C:/Program Files (x86)/Nmap/ninja.exe"
      - "C:/Program Files (x86)/Nmap/ninja"
      - "C:/Program Files (x86)/Nmap/samu.com"
      - "C:/Program Files (x86)/Nmap/samu.exe"
      - "C:/Program Files (x86)/Nmap/samu"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/ninja-build.com"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/ninja-build.exe"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/ninja-build"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/ninja.com"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/ninja.exe"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/ninja"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/samu.com"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/samu.exe"
      - "C:/Users/smidr/OneDrive/Desktop/github utils/vcpkg-2026.03.18/vcpkg-2026.03.18/samu"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/ninja-build.com"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/ninja-build.exe"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/ninja-build"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/ninja.com"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/ninja.exe"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/ninja"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/samu.com"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/samu.exe"
      - "C:/Users/smidr/AppData/Local/OpenAI/Codex/bin/samu"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/ninja-build.com"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/ninja-build.exe"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/ninja-build"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/ninja.com"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/ninja.exe"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/ninja"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/samu.com"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/samu.exe"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0/app/resources/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\smidr\\.sbx-denybin"
        - "C:\\Users\\smidr\\.codex\\tmp\\arg0\\codex-arg0uduYho"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Program Files\\Gpg4win\\..\\GnuPG\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Users\\smidr\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\smidr\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "C:\\Users\\smidr\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\smidr\\AppData\\Roaming\\npm"
        - "C:\\Program Files (x86)\\Nmap"
        - "C:\\Users\\smidr\\OneDrive\\Desktop\\github utils\\vcpkg-2026.03.18\\vcpkg-2026.03.18"
        - "C:\\Users\\smidr\\AppData\\Local\\OpenAI\\Codex\\bin"
        - "C:\\Program Files\\WindowsApps\\OpenAI.Codex_26.325.3894.0_x64__2p2nqsd0c76g0\\app\\resources"
...
